/**
 * @file Good and bad examples for guideline clauses, derived from the pinned guide and run with the full preset.
 */
import type { ImportGroups, Policy } from '../packages/rule-catalog/src/index';

export interface ClauseCase {
    /** Clause anchor from the guide. */
    clause: string;
    policy: Policy | 'both';
    importGroups?: ImportGroups;
    extension?: 'js' | 'jsx' | 'cjs' | 'ts' | 'tsx';
    /** Directory for the linted file, used by relative import examples. */
    directory?: string;
    /** Example that violates the clause. */
    bad?: string;
    /** Example that satisfies the clause. */
    good?: string;
    /** Oxlint rule codes (`plugin/rule`) that enforce the clause. */
    rules: string[];
    /** The bad example is not reported under this policy (a partial or overridden clause). */
    expectMiss?: boolean;
    /** The good example is reported under this policy (a sample setting conflicts with the clause). */
    expectConflict?: boolean;
    /** Omit the file overview comment that every fixture otherwise starts with. */
    bare?: boolean;
    /** Omit the final newline. */
    noFinalNewline?: boolean;
}

export const clauseGlobals = [
    '$', 'check', 'compute', 'convert', 'first', 'flag', 'items', 'report', 'second', 'source', 'third', 'userName',
];

const LONG = 'a'.repeat(130);
// Builds template substitutions in fixture source text without writing `${` inside a string literal.
const DOLLAR = '$';

export const clauseCases: ClauseCase[] = [
    {
        clause: 'references--prefer-const',
        policy: 'both',
        bad: 'let value = 1;\nreport(value);',
        good: 'const value = 1;\nreport(value);',
        rules: ['ag-compat/prefer-const'],
    },
    {
        clause: 'references--disallow-var',
        policy: 'both',
        bad: 'var count = 1;\ncount += 1;\nreport(count);',
        good: 'let count = 1;\ncount += 1;\nreport(count);',
        rules: ['ag-compat/no-var'],
    },
    {
        clause: 'references--block-scope',
        policy: 'both',
        bad: 'if (flag) {\n    const inner = 1;\n    report(inner);\n}\nreport(inner);',
        good: 'const outer = 1;\nreport(outer);',
        rules: ['ag-compat/no-undef'],
    },
    {
        clause: 'objects--quoted-props',
        policy: 'both',
        bad: "report({ 'first': 1, 'data-key': 2 });",
        good: "report({ first: 1, 'data-key': 2 });",
        rules: ['ag-compat/quote-props'],
    },
    {
        clause: 'objects--prototype-builtins',
        policy: 'both',
        bad: "report(source.hasOwnProperty('key'));",
        good: "report(Object.prototype.hasOwnProperty.call(source, 'key'));",
        rules: ['ag-compat/no-prototype-builtins'],
    },
    {
        clause: 'objects--rest-spread',
        policy: 'both',
        bad: 'report(Object.assign({}, source, { extra: 3 }));',
        good: 'report({ ...source, extra: 3 });',
        rules: ['ag-compat/prefer-object-spread'],
    },
    {
        clause: 'arrays--mapping',
        policy: 'both',
        bad: 'report([...items].map(String));',
        good: 'report(Array.from(items, String));',
        rules: ['ag/prefer-array-from-map'],
    },
    {
        clause: 'arrays--callback-return',
        policy: 'both',
        bad: 'report(items.map((item) => {\n    item.toString();\n}));',
        good: 'report(items.map((item) => item.toString()));',
        rules: ['ag-compat/array-callback-return'],
    },
    {
        clause: 'destructuring--object',
        policy: 'both',
        bad: 'const firstName = source.firstName;\nreport(firstName);',
        good: 'const { firstName } = source;\nreport(firstName);',
        rules: ['ag-compat/prefer-destructuring'],
    },
    {
        clause: 'destructuring--array',
        policy: 'both',
        bad: 'let head;\nhead = items[0];\nreport(head);',
        good: 'let head;\n[head] = items;\nreport(head);',
        rules: ['ag-compat/prefer-destructuring'],
    },
    {
        clause: 'destructuring--array',
        policy: 'compatibility',
        bad: 'const head = items[0];\nreport(head);',
        rules: ['ag-compat/prefer-destructuring'],
        expectMiss: true,
    },
    {
        clause: 'destructuring--array',
        policy: 'guideline',
        bad: 'const head = items[0];\nreport(head);',
        good: 'const [head] = items;\nreport(head);',
        rules: ['ag-compat/prefer-destructuring'],
    },
    {
        clause: 'strings--quotes',
        policy: 'both',
        bad: 'report("double");',
        good: "report('single');",
        rules: ['ag-compat/quotes'],
    },
    {
        clause: 'strings--quotes',
        policy: 'both',
        extension: 'ts',
        bad: 'type Mode = "light";\nreport(null as Mode | null);',
        good: "type Mode = 'light';\nreport(null as Mode | null);",
        rules: ['ag-compat/quotes'],
    },
    {
        clause: 'strings--line-length',
        policy: 'compatibility',
        bad: "report('first part of a message '\n    + 'second part of a message');",
        rules: ['ag/no-multiline-string-concat'],
        expectMiss: true,
    },
    {
        clause: 'strings--line-length',
        policy: 'guideline',
        bad: "report('first part of a message '\n    + 'second part of a message');",
        good: `report('${LONG}');`,
        rules: ['ag/no-multiline-string-concat', 'ag-compat/max-len'],
    },
    {
        clause: 'es6-template-literals',
        policy: 'both',
        bad: "report('Hello ' + userName + '!');",
        good: `report(\`Hello ${DOLLAR}{userName}!\`);`,
        rules: ['ag-compat/prefer-template', 'ag-compat/template-curly-spacing'],
    },
    {
        clause: 'strings--eval',
        policy: 'both',
        bad: "report(eval('first'));",
        good: 'report(first);',
        rules: ['ag-compat/no-eval'],
    },
    {
        clause: 'strings--escaping',
        policy: 'both',
        bad: "report('a \\i b');",
        good: "report('a i b');",
        rules: ['ag-compat/no-useless-escape'],
    },
    {
        clause: 'functions--iife',
        policy: 'both',
        bad: '(function () {\n    report(1);\n})();',
        good: '(function () {\n    report(1);\n}());',
        rules: ['ag-compat/wrap-iife'],
    },
    {
        clause: 'functions--in-blocks',
        policy: 'both',
        bad: 'if (flag) {\n    function test() {\n        report(1);\n    }\n    test();\n}',
        good: 'if (flag) {\n    const test = () => {\n        report(1);\n    };\n    test();\n}',
        rules: ['ag-compat/no-loop-func', 'ag-compat/no-inner-declarations'],
    },
    {
        clause: 'functions--arguments-shadow',
        policy: 'both',
        extension: 'cjs',
        bad: 'module.exports = function run(name, options, arguments) {\n    return arguments;\n};',
        good: 'module.exports = function run(name, options, args) {\n    return args;\n};',
        rules: ['ag-compat/no-shadow-restricted-names'],
    },
    {
        clause: 'es6-rest',
        policy: 'both',
        bad: "report(function concat() {\n    return Array.prototype.slice.call(arguments).join('');\n});",
        good: "report((...args) => args.join(''));",
        rules: ['ag-compat/prefer-rest-params'],
    },
    {
        clause: 'es6-default-parameters',
        policy: 'both',
        bad: 'report((options) => {\n    options = options || {};\n    return options;\n});',
        good: 'report((options = {}) => options);',
        rules: ['ag-compat/no-param-reassign'],
    },
    {
        clause: 'functions--default-side-effects',
        policy: 'both',
        bad: 'let counter = 1;\nreport((next = counter += 1) => next);',
        good: 'report((next = 1) => next);',
        rules: ['ag/no-default-side-effects'],
    },
    {
        clause: 'functions--defaults-last',
        policy: 'both',
        bad: 'report((options = {}, name) => [options, name]);',
        good: 'report((name, options = {}) => [options, name]);',
        rules: ['ag-compat/default-param-last'],
    },
    {
        clause: 'functions--defaults-last',
        policy: 'both',
        extension: 'ts',
        bad: 'report((options = {}, name: string) => [options, name]);',
        good: 'report((options = {}, name?: string) => [options, name]);',
        rules: ['eslint/default-param-last'],
    },
    {
        clause: 'functions--constructor',
        policy: 'both',
        bad: "report(new Function('a', 'b', 'return a + b'));",
        good: 'report((left, right) => left + right);',
        rules: ['ag-compat/no-new-func'],
    },
    {
        clause: 'functions--signature-spacing',
        policy: 'both',
        bad: 'report(function(){\n    return 1;\n});',
        good: 'report(function () {\n    return 1;\n});',
        rules: ['ag-compat/space-before-function-paren', 'ag-compat/space-before-blocks'],
    },
    {
        clause: 'functions--mutate-params',
        policy: 'both',
        bad: 'report((target) => {\n    target.key = 1;\n});',
        good: 'report((target) => ({ ...target, key: 1 }));',
        rules: ['ag-compat/no-param-reassign'],
    },
    {
        clause: 'functions--reassign-params',
        policy: 'both',
        bad: 'report((value) => {\n    value = 1;\n    return value;\n});',
        good: 'report((value) => {\n    const next = value + 1;\n    return next;\n});',
        rules: ['ag-compat/no-param-reassign'],
    },
    {
        clause: 'functions--spread-vs-apply',
        policy: 'both',
        bad: 'report(Math.max.apply(Math, items));',
        good: 'report(Math.max(...items));',
        rules: ['ag-compat/prefer-spread'],
    },
    {
        clause: 'functions--signature-invocation-indentation',
        policy: 'both',
        bad: 'report(first,\n    second);',
        good: 'report(\n    first,\n    second,\n);',
        rules: ['ag-compat/function-paren-newline'],
    },
    {
        clause: 'arrows--use-them',
        policy: 'both',
        bad: 'report(items.map(function (item) {\n    return item * 2;\n}));',
        good: 'report(items.map((item) => item * 2));',
        rules: ['ag-compat/prefer-arrow-callback', 'ag-compat/arrow-spacing'],
    },
    {
        clause: 'arrows--one-arg-parens',
        policy: 'both',
        bad: 'report(items.map(item => item * 2));',
        good: 'report(items.map((item) => item * 2));',
        rules: ['ag-compat/arrow-parens'],
    },
    {
        clause: 'whitespace--implicit-arrow-linebreak',
        policy: 'both',
        bad: 'report((item) =>\n    item.value);',
        good: 'report((item) => item.value);',
        rules: ['ag-compat/implicit-arrow-linebreak'],
    },
    {
        clause: 'constructors--use-class',
        policy: 'both',
        bad: 'function Queue() {}\nQueue.prototype.pop = () => null;\nreport(Queue);',
        good: 'class Queue {\n    pop() {\n        return this.last;\n    }\n}\nreport(Queue);',
        rules: ['ag/no-prototype-mutation'],
    },
    {
        clause: 'constructors--extends',
        policy: 'both',
        bad: 'function Queue() {}\nfunction PeekableQueue() {}\nPeekableQueue.prototype = Object.create(Queue.prototype);\n'
            + 'report(PeekableQueue);',
        good: 'class Queue {}\nreport(class PeekableQueue extends Queue {});',
        rules: ['ag/no-prototype-mutation'],
    },
    {
        clause: 'constructors--no-useless',
        policy: 'both',
        bad: 'report(class Jedi {\n    constructor() {}\n});',
        good: 'report(class Jedi {\n    speak() {\n        return this.name;\n    }\n});',
        rules: ['ag-compat/no-useless-constructor'],
    },
    {
        clause: 'classes--methods-use-this',
        policy: 'both',
        bad: 'report(class Foo {\n    bar() {\n        return 1;\n    }\n});',
        good: 'report(class Foo {\n    static bar() {\n        return 1;\n    }\n});',
        rules: ['ag-compat/class-methods-use-this'],
    },
    {
        clause: 'modules--use-them',
        policy: 'compatibility',
        bad: "const helper = require('./helper');\n\nmodule.exports = helper;",
        rules: ['import/no-commonjs'],
        expectMiss: true,
    },
    {
        clause: 'modules--use-them',
        policy: 'guideline',
        bad: "const helper = require('./helper');\n\nmodule.exports = helper;",
        good: "import { first } from './helpers';\n\nreport(first);",
        rules: ['import/no-commonjs', 'ag-import/no-amd'],
    },
    {
        clause: 'modules--no-wildcard',
        policy: 'compatibility',
        bad: "import * as helpers from './helpers';\n\nreport(helpers);",
        rules: ['import/no-namespace'],
        expectMiss: true,
    },
    {
        clause: 'modules--no-wildcard',
        policy: 'guideline',
        bad: "import * as helpers from './helpers';\n\nreport(helpers);",
        good: "import { first } from './helpers';\n\nreport(first);",
        rules: ['import/no-namespace'],
    },
    {
        clause: 'modules--no-export-from-import',
        policy: 'both',
        bad: "export { first, second } from './helpers';",
        good: "import { first, second } from './helpers';\n\nexport { first, second };",
        rules: ['ag/no-direct-reexport'],
    },
    {
        clause: 'modules--no-duplicate-imports',
        policy: 'both',
        bad: "import { first } from './helpers';\nimport { second } from './helpers';\n\nreport(first, second);",
        good: "import { first, second } from './helpers';\n\nreport(first, second);",
        rules: ['ag-import/no-duplicates'],
    },
    {
        clause: 'modules--no-mutable-exports',
        policy: 'both',
        bad: 'let count = 1;\nlet total = 2;\n\nexport { count, total };',
        good: 'const COUNT = 1;\nconst TOTAL = 2;\n\nexport { COUNT, TOTAL };',
        rules: ['ag-import/no-mutable-exports'],
    },
    {
        clause: 'modules--prefer-named-export',
        policy: 'compatibility',
        bad: 'export default function foo() {}',
        rules: ['import/no-default-export'],
        expectMiss: true,
    },
    {
        clause: 'modules--prefer-named-export',
        policy: 'guideline',
        bad: 'export default function foo() {}',
        good: 'export function foo() {}',
        rules: ['import/no-default-export', 'ag-import/prefer-default-export'],
    },
    {
        clause: 'modules--imports-first',
        policy: 'both',
        bad: "import { first } from './helpers';\n\nreport(first);\nimport { second } from './helpers';\n\nreport(second);",
        good: "import { first, second } from './helpers';\n\nreport(first);\nreport(second);",
        rules: ['ag-import/first'],
    },
    {
        clause: 'modules--multiline-imports-over-newlines',
        policy: 'both',
        bad: "import { first, fourth, second, third } from './helpers';\n\nreport(first, second, third, fourth);",
        good: "import {\n    first,\n    fourth,\n    second,\n    third,\n} from './helpers';\n\n"
            + 'report(first, second, third, fourth);',
        rules: ['ag-compat/object-curly-newline'],
    },
    {
        clause: 'modules--import-extensions',
        policy: 'both',
        bad: "import { first } from './helpers.js';\n\nreport(first);",
        good: "import { first } from './helpers';\n\nreport(first);",
        rules: ['ag-import/extensions'],
    },
    {
        clause: 'modules--import-grouping',
        policy: 'both',
        directory: 'src',
        bad: "import foo from './foo';\nimport fs from 'node:fs';\n\nreport(foo, fs);",
        good: "import fs from 'node:fs';\n\nimport foo from './foo';\n\nreport(foo, fs);",
        rules: ['ag-import/order'],
    },
    {
        clause: 'modules--import-grouping',
        policy: 'compatibility',
        directory: 'src',
        bad: "import fs from 'node:fs';\nimport bar from '../bar';\nimport foo from './foo';\n\nreport(fs, bar, foo);",
        rules: ['ag-import/order'],
        expectMiss: true,
    },
    {
        clause: 'modules--import-grouping',
        policy: 'guideline',
        importGroups: 'example',
        directory: 'src',
        bad: "import fs from 'node:fs';\nimport bar from '../bar';\nimport foo from './foo';\n\nreport(fs, bar, foo);",
        good: "import fs from 'node:fs';\nimport npmPackage from 'npm-package';\n\nimport bar from '../bar';\n\n"
            + "import foo from './foo';\n\nreport(fs, npmPackage, bar, foo);",
        rules: ['ag-import/order'],
    },
    {
        clause: 'modules--import-grouping',
        policy: 'guideline',
        importGroups: 'prose',
        directory: 'src',
        bad: "import fs from 'node:fs';\nimport npmPackage from 'npm-package';\n\nimport bar from '../bar';\n\n"
            + "import foo from './foo';\n\nreport(fs, npmPackage, bar, foo);",
        good: "import fs from 'node:fs';\n\nimport npmPackage from 'npm-package';\n\nimport bar from '../bar';\n\n"
            + "import foo from './foo';\n\nreport(fs, npmPackage, bar, foo);",
        rules: ['ag-import/order'],
    },
    {
        clause: 'modules--import-order',
        policy: 'compatibility',
        bad: "import second from 'b';\nimport first from 'a';\n\nreport(first, second);",
        rules: ['ag-import/order'],
        expectMiss: true,
    },
    {
        clause: 'modules--import-order',
        policy: 'guideline',
        bad: "import second from 'b';\nimport first from 'a';\n\nreport(first, second);",
        good: "import second from 'a';\nimport first from 'b';\n\nreport(first, second);",
        rules: ['ag-import/order'],
    },
    {
        clause: 'modules--import-member-order',
        policy: 'both',
        bad: "import { second, first } from './helpers';\n\nreport(first, second);",
        good: "import { first, second } from './helpers';\n\nreport(first, second);",
        rules: ['ag-import/order', 'ag-compat/sort-imports'],
    },
    {
        clause: 'modules--import-node-protocol',
        policy: 'both',
        bad: "import fs from 'fs';\n\nreport(fs);",
        good: "import fs from 'node:fs';\n\nreport(fs);",
        rules: ['unicorn/prefer-node-protocol'],
    },
    {
        clause: 'properties--dot',
        policy: 'both',
        bad: "report(source['jedi']);",
        good: 'report(source.jedi);',
        rules: ['ag-compat/dot-notation'],
    },
    {
        clause: 'properties--bracket',
        policy: 'both',
        bad: "report(source['jedi']);",
        good: 'report((property) => source[property]);',
        rules: ['ag-compat/dot-notation'],
    },
    {
        clause: 'es2016-properties--exponentiation-operator',
        policy: 'both',
        bad: 'report(Math.pow(2, 10));',
        good: 'report(2 ** 10);',
        rules: ['ag-compat/no-restricted-properties'],
    },
    {
        clause: 'variables--const',
        policy: 'both',
        bad: 'superPower = compute();',
        good: 'const superPower = compute();\nreport(superPower);',
        rules: ['ag-compat/no-undef', 'ag-compat/prefer-const'],
    },
    {
        clause: 'variables--one-const',
        policy: 'both',
        bad: 'const head = 1, tail = 2;\nreport(head, tail);',
        good: 'const head = 1;\nconst tail = 2;\nreport(head, tail);',
        rules: ['ag-compat/one-var'],
    },
    {
        clause: 'variables--no-chain-assignment',
        policy: 'both',
        bad: 'let head;\nlet tail;\nhead = tail = compute();\nreport(head, tail);',
        good: 'const head = compute();\nconst tail = head;\nreport(head, tail);',
        rules: ['ag-compat/no-multi-assign'],
    },
    {
        clause: 'variables--unary-increment-decrement',
        policy: 'both',
        bad: 'let count = 1;\ncount++;\nreport(count);',
        good: 'let count = 1;\ncount += 1;\nreport(count);',
        rules: ['ag-compat/no-plusplus'],
    },
    {
        clause: 'variables--linebreak',
        policy: 'both',
        bad: 'const result =\n    compute();\nreport(result);',
        good: 'const result = (\n    compute()\n);\nreport(result);',
        rules: ['ag-compat/max-len', 'ag-compat/operator-linebreak'],
    },
    {
        clause: 'variables--no-unused-vars',
        policy: 'both',
        bad: 'const unused = compute();',
        good: 'const used = compute();\nreport(used);',
        rules: ['ag-compat/no-unused-vars'],
    },
    {
        clause: 'variables--no-unused-vars',
        policy: 'both',
        extension: 'ts',
        bad: 'const unused: number = compute();',
        good: 'interface Shape {\n    area(size: number): number;\n}\nconst used: Shape | null = compute();\nreport(used);',
        rules: ['eslint/no-unused-vars'],
    },
    {
        clause: 'comparison--eqeqeq',
        policy: 'both',
        bad: 'report(source == 1);',
        good: 'report(source === 1);',
        rules: ['ag-compat/eqeqeq'],
    },
    {
        clause: 'comparison--switch-blocks',
        policy: 'both',
        bad: 'switch (source) {\n    case 1:\n        const value = 1;\n        report(value);\n        break;\n'
            + '    default:\n        break;\n}',
        good: 'switch (source) {\n    case 1: {\n        const value = 1;\n        report(value);\n        break;\n    }\n'
            + '    default:\n        break;\n}',
        rules: ['ag-compat/no-case-declarations'],
    },
    {
        clause: 'comparison--nested-ternaries',
        policy: 'both',
        bad: 'report(first ? 1 : second ? 2 : 3);',
        good: 'const fallback = second ? 2 : 3;\nreport(first ? 1 : fallback);',
        rules: ['ag-compat/no-nested-ternary'],
    },
    {
        clause: 'comparison--unneeded-ternary',
        policy: 'both',
        bad: 'report(flag ? true : false);',
        good: 'report(Boolean(flag));',
        rules: ['ag-compat/no-unneeded-ternary'],
    },
    {
        clause: 'comparison--no-mixed-operators',
        policy: 'both',
        bad: 'report(first && second || third);',
        good: 'report((first && second) || third);',
        rules: ['ag-compat/no-mixed-operators'],
    },
    {
        clause: 'blocks--braces',
        policy: 'both',
        bad: 'if (flag) report(1);',
        good: 'if (flag) {\n    report(1);\n}',
        rules: ['ag-compat/curly', 'ag-compat/brace-style'],
    },
    {
        clause: 'blocks--cuddled-elses',
        policy: 'both',
        bad: 'if (flag) {\n    report(1);\n}\nelse {\n    report(2);\n}',
        good: 'if (flag) {\n    report(1);\n} else {\n    report(2);\n}',
        rules: ['ag-compat/brace-style'],
    },
    {
        clause: 'blocks--no-else-return',
        policy: 'both',
        bad: 'report(() => {\n    if (flag) {\n        return 1;\n    } else {\n        return 2;\n    }\n});',
        good: 'report(() => {\n    if (flag) {\n        return 1;\n    }\n\n    return 2;\n});',
        rules: ['ag-compat/no-else-return'],
    },
    {
        clause: 'control-statements',
        policy: 'both',
        bad: 'if (\n    first === 123 &&\n    second === 1\n) {\n    report(1);\n}',
        good: 'if (\n    first === 123\n    && second === 1\n) {\n    report(1);\n}',
        rules: ['ag-compat/operator-linebreak', 'ag/multiline-condition-layout'],
    },
    {
        clause: 'control-statements',
        policy: 'compatibility',
        bad: 'if (first === 123\n    && second === 1) {\n    report(1);\n}',
        rules: ['ag-compat/operator-linebreak', 'ag/multiline-condition-layout'],
        expectMiss: true,
    },
    {
        clause: 'control-statements',
        policy: 'guideline',
        bad: 'if (first === 123\n    && second === 1) {\n    report(1);\n}',
        rules: ['ag/multiline-condition-layout'],
    },
    {
        clause: 'control-statement--value-selection',
        policy: 'both',
        bad: '!flag && report(1);',
        good: 'if (!flag) {\n    report(1);\n}',
        rules: ['ag-compat/no-unused-expressions'],
    },
    {
        clause: 'comments--multiline',
        policy: 'both',
        bad: '/* make() returns a new element\n   based on the passed in tag name */\nreport(1);',
        good: '/**\n * make() returns a new element\n * based on the passed-in tag name\n */\nreport(1);',
        rules: ['ag/require-docblock'],
    },
    {
        clause: 'comments--multiline',
        policy: 'compatibility',
        bad: '// make() returns a new element\n// based on the passed in tag name\nreport(1);',
        rules: ['ag/require-docblock'],
        expectMiss: true,
    },
    {
        clause: 'comments--multiline',
        policy: 'guideline',
        bad: '// make() returns a new element\n// based on the passed in tag name\nreport(1);',
        rules: ['ag/require-docblock'],
    },
    {
        clause: 'comments--singleline',
        policy: 'compatibility',
        bad: 'report(1); // is current tab',
        rules: ['ag-compat/line-comment-position', 'ag-compat/lines-around-comment'],
        expectMiss: true,
    },
    {
        clause: 'comments--singleline',
        policy: 'guideline',
        bad: "report('fetching type...');\n// set the default type\nreport(1); // is current tab",
        good: "report('fetching type...');\n\n// set the default type\nreport(1);\n\nif (flag) {\n"
            + '    // set the default type\n    report(2);\n}',
        rules: ['ag-compat/line-comment-position', 'ag-compat/lines-around-comment'],
    },
    {
        // The clause covers single-line comments; block comments need no preceding blank line.
        clause: 'comments--singleline',
        policy: 'guideline',
        good: 'report({\n    first: 1,\n    /**\n     * Documents the property.\n     */\n    second: 2,\n});',
        rules: ['ag-compat/line-comment-position', 'ag-compat/lines-around-comment'],
    },
    {
        clause: 'comments--singleline',
        policy: 'guideline',
        extension: 'ts',
        good: 'interface Tab {\n    // is current tab\n    active: boolean;\n}\nreport(null as Tab | null);',
        rules: ['ag-style/lines-around-comment'],
    },
    {
        clause: 'comments--spaces',
        policy: 'both',
        bad: '//is current tab\nreport(1);',
        good: '// is current tab\nreport(1);',
        rules: ['ag-compat/spaced-comment'],
    },
    {
        clause: 'comments-jsdoc',
        policy: 'both',
        bare: true,
        bad: 'report(1);',
        good: '/**\n * @file Reports a value.\n */\n\nreport(1);',
        rules: ['ag-jsdoc/require-file-overview'],
    },
    {
        clause: 'whitespace--spaces',
        policy: 'both',
        bad: 'if (flag) {\n  report(1);\n}',
        good: 'if (flag) {\n    report(1);\n}',
        rules: ['ag-compat/indent', 'ag-react/jsx-indent', 'ag-react/jsx-indent-props'],
    },
    {
        clause: 'whitespace--spaces',
        policy: 'compatibility',
        extension: 'jsx',
        good: 'report(\n    <div>\n        <span />\n    </div>,\n);',
        rules: ['ag-react/jsx-indent'],
        expectConflict: true,
    },
    {
        clause: 'whitespace--spaces',
        policy: 'guideline',
        extension: 'jsx',
        bad: 'report(\n    <div>\n      <span />\n    </div>,\n);',
        good: 'report(\n    <div>\n        <span />\n    </div>,\n);',
        rules: ['ag-react/jsx-indent', 'ag-react/jsx-indent-props'],
    },
    {
        clause: 'whitespace--before-blocks',
        policy: 'both',
        bad: 'if (flag){\n    report(1);\n}',
        good: 'if (flag) {\n    report(1);\n}',
        rules: ['ag-compat/space-before-blocks'],
    },
    {
        clause: 'whitespace--before-blocks',
        policy: 'both',
        extension: 'ts',
        bad: 'interface Shape{\n    area: number;\n}\nreport(null as Shape | null);',
        good: 'interface Shape {\n    area: number;\n}\nreport(null as Shape | null);',
        rules: ['ag-style/space-before-blocks'],
    },
    {
        clause: 'whitespace--around-keywords',
        policy: 'both',
        bad: 'if(flag) {\n    report(1);\n}',
        good: 'if (flag) {\n    report(1);\n}',
        rules: ['ag-compat/keyword-spacing'],
    },
    {
        clause: 'whitespace--infix-ops',
        policy: 'both',
        bad: 'report(first+second);',
        good: 'report(first + second);',
        rules: ['ag-compat/space-infix-ops'],
    },
    {
        clause: 'whitespace--infix-ops',
        policy: 'both',
        extension: 'ts',
        bad: 'type Value = string|number;\nreport(null as Value | null);',
        good: 'type Value = string | number;\nreport(null as Value | null);',
        rules: ['ag-style/space-infix-ops'],
    },
    {
        clause: 'whitespace--newline-at-end',
        policy: 'both',
        noFinalNewline: true,
        bad: 'report(1);',
        rules: ['ag-compat/eol-last'],
    },
    {
        clause: 'whitespace--newline-at-end',
        policy: 'both',
        good: 'report(1);',
        rules: ['ag-compat/eol-last'],
    },
    {
        clause: 'whitespace--chains',
        policy: 'both',
        bad: "$('#items').find('.selected').highlight().end().find('.open').updateCount();",
        good: "$('#items')\n    .find('.selected')\n    .highlight()\n    .end()\n    .find('.open')\n    .updateCount();",
        rules: ['ag-compat/newline-per-chained-call', 'ag-compat/no-whitespace-before-property'],
    },
    {
        clause: 'whitespace--chains',
        policy: 'compatibility',
        bad: "report(items.filter(check).map(convert).join(','));",
        rules: ['ag-compat/newline-per-chained-call'],
        expectMiss: true,
    },
    {
        clause: 'whitespace--chains',
        policy: 'guideline',
        bad: "report(items.filter(check).map(convert).join(','));",
        good: "report(items\n    .filter(check)\n    .map(convert)\n    .join(','));",
        rules: ['ag-compat/newline-per-chained-call'],
    },
    {
        clause: 'whitespace--after-blocks',
        policy: 'compatibility',
        bad: 'if (flag) {\n    report(1);\n}\nreport(2);',
        rules: ['ag-compat/padding-line-between-statements'],
        expectMiss: true,
    },
    {
        clause: 'whitespace--after-blocks',
        policy: 'guideline',
        bad: 'if (flag) {\n    report(1);\n}\nreport(2);',
        good: 'if (flag) {\n    report(1);\n}\n\nreport(2);',
        rules: ['ag-compat/padding-line-between-statements'],
    },
    {
        clause: 'whitespace--after-blocks',
        policy: 'guideline',
        bad: 'report({\n    foo() {\n        return 1;\n    },\n    bar() {\n        return 2;\n    },\n});',
        rules: ['ag-compat/padding-line-between-statements'],
        expectMiss: true,
    },
    {
        clause: 'whitespace--padded-blocks',
        policy: 'both',
        bad: 'if (flag) {\n\n    report(1);\n\n}',
        good: 'if (flag) {\n    report(1);\n}',
        rules: ['ag-compat/padded-blocks'],
    },
    {
        clause: 'whitespace--no-multiple-blanks',
        policy: 'both',
        bad: 'report(1);\n\n\nreport(2);',
        good: 'report(1);\n\nreport(2);',
        rules: ['ag-compat/no-multiple-empty-lines'],
    },
    {
        clause: 'whitespace--in-parens',
        policy: 'both',
        bad: 'report( 1 );',
        good: 'report(1);',
        rules: ['ag-compat/space-in-parens'],
    },
    {
        clause: 'whitespace--in-brackets',
        policy: 'both',
        bad: 'report([ 1, 2 ]);',
        good: 'report([1, 2]);',
        rules: ['ag-compat/array-bracket-spacing'],
    },
    {
        clause: 'whitespace--in-braces',
        policy: 'both',
        bad: 'report({first: 1});',
        good: 'report({ first: 1 });',
        rules: ['ag-compat/object-curly-spacing'],
    },
    {
        clause: 'whitespace--in-braces',
        policy: 'both',
        extension: 'ts',
        bad: 'type Value = {first: string};\nreport(null as Value | null);',
        good: 'type Value = { first: string };\nreport(null as Value | null);',
        rules: ['ag-style/object-curly-spacing'],
    },
    {
        clause: 'whitespace--max-len',
        policy: 'both',
        bad: `report(first, second, third, ${Array.from({ length: 12 }, () => 'first + second').join(', ')});`,
        good: 'report(\n    first,\n    second,\n    third,\n);',
        rules: ['ag-compat/max-len'],
    },
    {
        clause: 'whitespace--block-spacing',
        policy: 'both',
        bad: 'report(() => {return 1;});',
        good: 'report(() => { return 1; });',
        rules: ['ag-compat/block-spacing'],
    },
    {
        clause: 'whitespace--comma-spacing',
        policy: 'both',
        bad: 'report(first ,second);',
        good: 'report(first, second);',
        rules: ['ag-compat/comma-spacing'],
    },
    {
        clause: 'whitespace--computed-property-spacing',
        policy: 'both',
        bad: "const key = 'name';\nreport(source[ key ]);",
        good: "const key = 'name';\nreport(source[key]);",
        rules: ['ag-compat/computed-property-spacing'],
    },
    {
        clause: 'whitespace--func-call-spacing',
        policy: 'both',
        bad: 'report (1);',
        good: 'report(1);',
        rules: ['ag-compat/func-call-spacing'],
    },
    {
        clause: 'whitespace--key-spacing',
        policy: 'both',
        bad: 'report({ first:1 });',
        good: 'report({ first: 1 });',
        rules: ['ag-compat/key-spacing'],
    },
    {
        clause: 'whitespace--key-spacing',
        policy: 'both',
        extension: 'ts',
        bad: 'interface Shape {\n    area : number;\n}\nreport(null as Shape | null);',
        good: 'interface Shape {\n    area: number;\n}\nreport(null as Shape | null);',
        rules: ['ag-style/key-spacing'],
    },
    {
        clause: 'whitespace--no-trailing-spaces',
        policy: 'both',
        bad: 'report(1);   \nreport(2);',
        good: 'report(1);\nreport(2);',
        rules: ['ag-compat/no-trailing-spaces'],
    },
    {
        clause: 'whitespace--no-multiple-empty-lines',
        policy: 'both',
        bad: 'report(1);\n',
        good: 'report(1);',
        rules: ['ag-compat/no-multiple-empty-lines'],
    },
    {
        clause: 'commas--leading-trailing',
        policy: 'both',
        bad: 'report([\n    first\n    , second,\n]);',
        good: 'report([\n    first,\n    second,\n]);',
        rules: ['ag-compat/comma-style'],
    },
    {
        clause: 'commas--dangling',
        policy: 'both',
        bad: 'report({\n    first: 1,\n    second: 2\n});',
        good: 'report({\n    first: 1,\n    second: 2,\n});',
        rules: ['ag-compat/comma-dangle'],
    },
    {
        clause: 'commas--dangling',
        policy: 'both',
        extension: 'ts',
        bad: "enum Color {\n    Red = 'Red',\n    Green = 'Green'\n}\nreport(Color);",
        good: "enum Color {\n    Red = 'Red',\n    Green = 'Green',\n}\nreport(Color);",
        rules: ['ag-style/comma-dangle'],
    },
    {
        clause: 'semicolons--required',
        policy: 'both',
        bad: 'report(1)',
        good: 'report(1);',
        rules: ['ag-compat/semi'],
    },
    {
        clause: 'semicolons--required',
        policy: 'both',
        extension: 'ts',
        bad: 'type Value = string\nreport(null as Value | null);',
        good: 'type Value = string;\nreport(null as Value | null);',
        rules: ['ag-style/semi'],
    },
    {
        clause: 'coercion--strings',
        policy: 'both',
        bad: 'report(new String(source));',
        good: 'report(String(source));',
        rules: ['ag-compat/no-new-wrappers'],
    },
    {
        clause: 'coercion--numbers',
        policy: 'both',
        bad: 'report(parseInt(source));',
        good: 'report(parseInt(source, 10));',
        rules: ['ag-compat/radix', 'ag-compat/no-new-wrappers'],
    },
    {
        clause: 'coercion--comment-deviations',
        policy: 'both',
        good: '/**\n * Bitshifting the String to coerce it to a Number made it a lot faster.\n */\nreport(source >> 0);',
        rules: ['ag-compat/no-bitwise'],
        expectConflict: true,
    },
    {
        clause: 'coercion--booleans',
        policy: 'both',
        bad: 'report(new Boolean(flag));',
        good: 'report(Boolean(flag));',
        rules: ['ag-compat/no-new-wrappers'],
    },
    {
        clause: 'naming--descriptive',
        policy: 'compatibility',
        bad: 'const q = compute();\nreport(q);',
        rules: ['ag-compat/id-length'],
        expectMiss: true,
    },
    {
        clause: 'naming--descriptive',
        policy: 'guideline',
        bad: 'const q = compute();\nreport(q);',
        good: 'const query = compute();\nreport(query);',
        rules: ['ag-compat/id-length'],
    },
    {
        clause: 'naming--camelCase',
        policy: 'both',
        bad: 'const snake_case = compute();\nreport(snake_case);',
        good: 'const camelCase = compute();\nreport(camelCase);',
        rules: ['ag-compat/camelcase'],
    },
    {
        clause: 'naming--PascalCase',
        policy: 'both',
        bad: 'const user = class {};\nreport(new user());',
        good: 'class User {}\nreport(new User());',
        rules: ['ag-compat/new-cap'],
    },
    {
        clause: 'naming--leading-underscore',
        policy: 'both',
        bad: 'const _hidden = compute();\nreport(_hidden);',
        good: 'const hidden = compute();\nreport(hidden);',
        rules: ['ag-compat/no-underscore-dangle'],
    },
    {
        clause: 'naming--self-this',
        policy: 'both',
        bad: 'report(function make() {\n    const self = this;\n    return () => self;\n});',
        good: 'report(function make() {\n    return () => this;\n});',
        rules: ['unicorn/no-this-assignment'],
    },
    {
        clause: 'naming--constants',
        policy: 'guideline',
        bad: "const childCombinator = '>';\nreport(childCombinator);",
        good: "const CHILD_COMBINATOR = '>';\nreport(CHILD_COMBINATOR);",
        rules: ['ag/constant-name'],
    },
    {
        clause: 'naming--constants',
        policy: 'guideline',
        bad: "report(() => {\n    const childCombinator = '>';\n    return childCombinator;\n});",
        rules: ['ag/constant-name'],
        expectMiss: true,
    },
    {
        clause: 'accessors--no-getters-setters',
        policy: 'both',
        bad: 'report(class Dragon {\n    get age() {\n        return this.value;\n    }\n});',
        good: 'report(class Dragon {\n    getAge() {\n        return this.value;\n    }\n});',
        rules: ['ag/no-accessors'],
    },
    {
        clause: 'accessors--no-getters-setters',
        policy: 'both',
        extension: 'ts',
        bad: 'interface Dragon {\n    get age(): number;\n}\nreport(null as Dragon | null);',
        good: 'interface Dragon {\n    getAge(): number;\n}\nreport(null as Dragon | null);',
        rules: ['ag/no-accessors'],
    },
    {
        clause: 'standard-library--isnan',
        policy: 'both',
        bad: 'report(isNaN(source));',
        good: 'report(Number.isNaN(source));',
        rules: ['ag-compat/no-restricted-globals'],
    },
    {
        clause: 'standard-library--isfinite',
        policy: 'both',
        bad: 'report(isFinite(source));',
        good: 'report(Number.isFinite(source));',
        rules: ['ag-compat/no-restricted-globals'],
    },
    {
        clause: 'typescript--enum-naming-conventions',
        policy: 'both',
        extension: 'ts',
        bad: "enum COLOR {\n    RED = 'RED',\n}\nreport(COLOR);",
        good: "enum Color {\n    Red = 'Red',\n}\nreport(Color);",
        rules: ['ag/enum-name'],
    },
    {
        clause: 'typescript--caught-error-type',
        policy: 'both',
        extension: 'ts',
        bad: 'try {\n    report(1);\n} catch (error: any) {\n    report(error);\n}',
        good: 'try {\n    report(1);\n} catch (error: unknown) {\n    report(error);\n}',
        rules: ['ag/unknown-catch'],
    },
    // Gaps and additions found by the clause-by-clause audit.
    {
        clause: 'objects--rest-spread',
        policy: 'both',
        bad: 'const original = { first: 1 };\nconst copy = Object.assign(original, { second: 2 });\ndelete copy.first;\nreport(copy);',
        rules: ['ag-compat/prefer-object-spread'],
        expectMiss: true,
    },
    {
        clause: 'arrays--from-array-like',
        policy: 'guideline',
        bad: 'report(Array.prototype.slice.call(source));',
        good: 'report(Array.from(source));',
        rules: ['ag/prefer-array-from'],
    },
    {
        clause: 'es6-template-literals',
        policy: 'compatibility',
        bad: "report(['How are you, ', userName, '?'].join());",
        rules: ['ag-compat/prefer-template', 'ag/prefer-template-over-join'],
        expectMiss: true,
    },
    {
        clause: 'es6-template-literals',
        policy: 'guideline',
        bad: "report(['How are you, ', userName, '?'].join());",
        rules: ['ag/prefer-template-over-join'],
    },
    {
        clause: 'es6-rest',
        policy: 'compatibility',
        bad: 'report(function count() {\n    return arguments.length;\n});',
        rules: ['ag-compat/prefer-rest-params', 'ag/no-arguments'],
        expectMiss: true,
    },
    {
        clause: 'es6-rest',
        policy: 'guideline',
        bad: 'report(function count() {\n    return arguments.length;\n});',
        good: 'report((...args) => args.length);',
        rules: ['ag/no-arguments'],
    },
    {
        clause: 'functions--default-side-effects',
        policy: 'both',
        bad: 'report((next = items.push(1)) => next);',
        rules: ['ag/no-default-side-effects'],
        expectMiss: true,
    },
    {
        clause: 'functions--default-side-effects',
        policy: 'both',
        bad: 'report((next = delete source.key) => next);',
        rules: ['ag/no-default-side-effects'],
    },
    {
        clause: 'functions--mutate-params',
        policy: 'compatibility',
        bad: 'report((acc) => {\n    acc.key = 1;\n    return acc;\n});',
        rules: ['ag-compat/no-param-reassign'],
        expectMiss: true,
    },
    {
        clause: 'functions--mutate-params',
        policy: 'guideline',
        bad: 'report((acc) => {\n    acc.key = 1;\n    return acc;\n});',
        rules: ['ag-compat/no-param-reassign'],
    },
    {
        clause: 'functions--mutate-params',
        policy: 'guideline',
        bad: 'report((list) => {\n    list.push(1);\n    return list;\n});',
        rules: ['ag-compat/no-param-reassign'],
        expectMiss: true,
    },
    {
        clause: 'functions--spread-vs-apply',
        policy: 'both',
        bad: 'report(new (Function.prototype.bind.apply(Date, [null, 2016, 8, 5]))());',
        rules: ['ag-compat/prefer-spread'],
        expectMiss: true,
    },
    {
        clause: 'constructors--use-class',
        policy: 'compatibility',
        bad: 'function Queue() {}\nObject.assign(Queue.prototype, { pop() {\n    return this.last;\n} });\nreport(Queue);',
        rules: ['ag/no-prototype-mutation'],
        expectMiss: true,
    },
    {
        clause: 'constructors--use-class',
        policy: 'guideline',
        bad: 'function Queue() {}\nObject.assign(Queue.prototype, { pop() {\n    return this.last;\n} });\nreport(Queue);',
        rules: ['ag/no-prototype-mutation'],
    },
    {
        clause: 'constructors--use-class',
        policy: 'guideline',
        bad: 'function Queue(contents = []) {\n    this.queue = [...contents];\n}\nreport(new Queue());',
        rules: ['ag/no-prototype-mutation'],
        expectMiss: true,
    },
    {
        clause: 'constructors--extends',
        policy: 'compatibility',
        bad: 'function Queue() {}\nfunction PeekableQueue() {}\nObject.setPrototypeOf(PeekableQueue, Queue);\nreport(PeekableQueue);',
        rules: ['ag/no-prototype-mutation'],
        expectMiss: true,
    },
    {
        clause: 'constructors--extends',
        policy: 'guideline',
        bad: 'function Queue() {}\nfunction PeekableQueue() {}\nObject.setPrototypeOf(PeekableQueue, Queue);\nreport(PeekableQueue);',
        rules: ['ag/no-prototype-mutation'],
    },
    {
        clause: 'constructors--extends',
        policy: 'guideline',
        bad: 'function Queue() {}\nfunction PeekableQueue(...contents) {\n    Queue.apply(this, contents);\n}\nreport(PeekableQueue);',
        rules: ['ag/no-prototype-mutation'],
        expectMiss: true,
    },
    {
        clause: 'modules--use-them',
        policy: 'guideline',
        extension: 'ts',
        bad: "import fs = require('node:fs');\n\nreport(fs);",
        rules: ['typescript/no-require-imports', 'import/no-commonjs'],
    },
    {
        clause: 'modules--use-them',
        policy: 'guideline',
        extension: 'ts',
        bad: 'const value = 1;\n\nexport = value;',
        rules: ['typescript/no-require-imports', 'import/no-commonjs', 'ag-import/no-amd'],
        expectMiss: true,
    },
    {
        clause: 'modules--no-duplicate-imports',
        policy: 'guideline',
        extension: 'ts',
        bad: "import type { Shape } from './shapes';\nimport { area } from './shapes';\n\nreport(area, null as Shape | null);",
        good: "import { area, type Shape } from './shapes';\n\nreport(area, null as Shape | null);",
        rules: ['ag-import/no-duplicates'],
    },
    {
        clause: 'modules--import-grouping',
        policy: 'guideline',
        importGroups: 'example',
        directory: 'src',
        bad: "import axios from 'axios';\nimport fs from 'node:fs';\n\nreport(axios, fs);",
        good: "import fs from 'node:fs';\nimport axios from 'axios';\n\nimport bar from '../bar';\n\nreport(fs, axios, bar);",
        rules: ['ag-import/order'],
    },
    {
        clause: 'comparison--eqeqeq',
        policy: 'compatibility',
        bad: 'report(source == null);',
        rules: ['ag-compat/eqeqeq'],
        expectMiss: true,
    },
    {
        clause: 'comparison--eqeqeq',
        policy: 'guideline',
        bad: 'report(source == null);',
        good: 'report(source === null || source === undefined);',
        rules: ['ag-compat/eqeqeq'],
    },
    {
        clause: 'comparison--switch-blocks',
        policy: 'guideline',
        good: 'switch (source) {\n    case 1: {\n        report(1);\n        break;\n    }\n    case 2: {\n        report(2);\n        break;\n    }\n'
            + '    default:\n        break;\n}',
        rules: ['ag-compat/padding-line-between-statements'],
    },
    {
        clause: 'control-statements',
        policy: 'guideline',
        bad: 'if ((first === 123 || second === 1) && check(third) && convert(flag)) {\n    report(1);\n}',
        rules: ['ag/multiline-condition-layout'],
        expectMiss: true,
    },
    {
        clause: 'comments--singleline',
        policy: 'guideline',
        bad: 'report(1);\n/* is current tab */\nreport(2);',
        rules: ['ag-compat/line-comment-position', 'ag-compat/lines-around-comment'],
        expectMiss: true,
    },
    {
        clause: 'comments--spaces',
        policy: 'compatibility',
        bad: '/**\n *make() returns a new element\n */\nreport(1);',
        rules: ['ag-compat/spaced-comment', 'ag/docblock-spacing'],
        expectMiss: true,
    },
    {
        clause: 'comments--spaces',
        policy: 'guideline',
        bad: '/**\n *make() returns a new element\n */\nreport(1);',
        good: '/**\n * make() returns a new element\n */\nreport(1);',
        rules: ['ag/docblock-spacing'],
    },
    {
        clause: 'comments--actionitems',
        policy: 'guideline',
        good: '// author name is not required\n// for future changes\n// TODO(author): blablabla\nreport(1);',
        rules: ['ag/require-docblock'],
    },
    {
        clause: 'whitespace--chains',
        policy: 'guideline',
        good: "report($('#items')\n    .find('.selected')\n    .enter().append('svg'));",
        rules: ['ag-compat/newline-per-chained-call'],
        expectConflict: true,
    },
    {
        clause: 'whitespace--max-len',
        policy: 'compatibility',
        good: `report('${LONG}');`,
        rules: ['ag-compat/max-len'],
        expectConflict: true,
    },
    {
        clause: 'whitespace--max-len',
        policy: 'guideline',
        bad: `report(first, second, third, '', ${Array.from({ length: 12 }, () => 'first + second').join(', ')});`,
        rules: ['ag-compat/max-len'],
        expectMiss: true,
    },
    {
        clause: 'coercion--strings',
        policy: 'compatibility',
        bad: "report(source + '');",
        rules: ['ag-compat/no-implicit-coercion'],
        expectMiss: true,
    },
    {
        clause: 'coercion--strings',
        policy: 'guideline',
        bad: "report('' + source);",
        good: 'report(String(source));',
        rules: ['ag-compat/no-implicit-coercion'],
    },
    {
        clause: 'coercion--numbers',
        policy: 'compatibility',
        bad: 'report(+source);',
        rules: ['ag-compat/no-implicit-coercion'],
        expectMiss: true,
    },
    {
        clause: 'coercion--numbers',
        policy: 'guideline',
        bad: 'report(+source);',
        good: 'report(Number(source));',
        rules: ['ag-compat/no-implicit-coercion'],
    },
    {
        clause: 'naming--camelCase',
        policy: 'both',
        bad: 'const MyInstance = compute();\nreport(MyInstance);',
        rules: ['ag-compat/camelcase'],
        expectMiss: true,
    },
    {
        clause: 'functions--iife',
        policy: 'guideline',
        good: '(function () {\n    report(1);\n}());',
        rules: ['ag-compat/func-names'],
    },
];
